### ISSUE TITLE
IntelliSense Not Working

### ISSUE THREAD

**Issue by jesshhu** [dotnet/vscode-csharp#4192]
Issue Type: <b>Bug</b>

I'm writing a selenium code, on my first create of the script IntelliSense is working, providing insights and options on what command to choose and also referencing cs files to other files using "using" command. But after sometime it stop working until now its not working. I already restart the VS Code, still no luck. Or Did I do something wrong, Can you help? I'm not really good in coding hope you can help me. Thank you!

Extension version: 1.23.5
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.61GB (1.78GB free)|
|Process Argv|--crash-reporter-id ce351d61-165c-442f-9137-6358f64cd873|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
@jesshhu Sorry you are running into issues. Can you please share the OmniSharp log from the Output pane for one of the runs where you are not getting intellisense?

**Comment by thiago-nsjob** [comment]
Hey @JoeRobich, 


  I've been experiencing the same problem as @jesshhu after installing 1.51 (not sure if it is related).  I created a new console app with "dotnet new console" and this is the intellisense I have : 
![image](https://user-images.githubusercontent.com/22122469/98587634-6af8dd80-2298-11eb-955f-61a59a7dcd3c.png)

here is my omnisharp startup log:
[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.6.30128.74 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            2: Visual Studio Build Tools 2017 15.9.28307.1274 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            3: Visual Studio Professional 2017 15.9.28307.586 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            4: StandAlone 16.8.0 - "c:\Users\...\.vscode\extensions\ms-dotnettools.csharp-1.23.5\.omnisharp\1.37.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.6.30128.74 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\...\Documents\Projects\test_omnisharp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\..\Documents\Projects\test_omnisharp'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\...\Documents\Projects\test_omnisharp\test_omnisharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\...\Documents\Projects\test_omnisharp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\...\Documents\Projects\test_omnisharp\test_omnisharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\...\Documents\Projects\test_omnisharp' on host 14644.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\...\Documents\Projects\test_omnisharp\test_omnisharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\...\Documents\Projects\test_omnisharp\test_omnisharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: test_omnisharp

I also tried some generics, and it loads one suggestion at a time:
![image](https://user-images.githubusercontent.com/22122469/98588034-068a4e00-2299-11eb-94e1-4c4aacc59ea7.png)


I tried the same things(closing, restarting, installing the c# extension again). No solution so far

**Comment by thiago-nsjob** [comment]
So, I decided to rollback to vs 1.50, and it worked...

![image](https://user-images.githubusercontent.com/22122469/98589236-fc694f00-229a-11eb-8442-2757b8f6e6c3.png)

@jesshhu [here ](https://code.visualstudio.com/updates/v1_50)is the link of the previous version if you want a work around for now.

**Comment by JoeRobich** [comment]
> Registered MSBuild instance: Visual Studio Professional 2019 16.6.30128.74 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"

@thiago-nsjob Noticing the CodeLens above your `x.` line in your first post. That would seem to indicate that the backing buffer had become out of sync with the editor. (cc: @333fred for your thoughts). Would you mind opening a separate issue for this problem, since we can't be sure it is the same one @jesshhu is experiencing?

**Comment by jesshhu** [comment]
Hi @JoeRobich I think @thiago-nsjob issue is the same on what I'm experiencing. but on my side no light bulb icon is appearing and it only provide the (abc) suggestion only though it already reference to certain packages such in selenium. I'll try to take some screenshots.

We'll try to replicate to my other laptop as well if I will experience the issue, I installed it in my other laptop. 

I'll try also the rollback to old version if it will work @thiago-nsjob 

Thank you!

**Comment by jesshhu** [comment]
I think this would be the expected

![image](https://user-images.githubusercontent.com/63313429/98653188-b0d8a300-2377-11eb-869e-60e5d536e753.png)

That I can see the lightbulb icon

But when creating new cs files

![image](https://user-images.githubusercontent.com/63313429/98653394-f301e480-2377-11eb-8dbd-a05197d96cfd.png)
![image](https://user-images.githubusercontent.com/63313429/98653449-00b76a00-2378-11eb-97de-6ec23cdcdf5e.png)

I don't know what I'm missing, I'm just following some tutorials online in using Selenium, C# and NUnit

**Comment by jesshhu** [comment]
This is from my other Machine

![image](https://user-images.githubusercontent.com/63313429/98655622-a10e8e00-237a-11eb-8916-fbe00566f33d.png)

the from later dates, the bulb is showing and now its not working, so no suggestions, though I can manually input but its suggesting to create a var, on what I remember.

Also I've just notice something in the referencing above

![image](https://user-images.githubusercontent.com/63313429/98655988-19754f00-237b-11eb-81e2-981da00530a1.png)

they're not the same with my other created one.

**Comment by jesshhu** [comment]
![image](https://user-images.githubusercontent.com/63313429/98656324-80930380-237b-11eb-8946-bef7e9e17fb6.png)

**Comment by 333fred** [comment]
Is this specifically new files? Can you try the latest prerelease and see if that solves it? https://github.com/OmniSharp/omnisharp-vscode/issues/4174#issuecomment-722667648

**Comment by Katekko** [comment]
@333fred Even with the last prerelease here its not working, idk what can I do...

I'm getting: `[fail]: OmniSharp.MSBuild.ProjectManager Attempted to update project that is not loaded: `

**Comment by 333fred** [comment]
@Katekko that sounds unrelated to any incremental changes. Can you please open a separate bug, and provide exact reproduction steps?

**Comment by Katekko** [comment]
> @Katekko that sounds unrelated to any incremental changes. Can you please open a separate bug, and provide exact reproduction steps?

https://github.com/OmniSharp/omnisharp-vscode/issues/4201

Done.

**Comment by BrightSoul** [comment]
I also got the same problem as OP with v1.23.5. 
I can't tell for sure if the culprit is that version in particular. The extension has been behaving terrible for me in the last few revisions.

```
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

Anyway, the issue is I don't get intellisense and code lens is in the wrong place.

![issue](https://user-images.githubusercontent.com/1888641/98851931-3c753100-2457-11eb-9dcf-d7d5173aef8f.png)


I'm leaving the log here, in case you'll find anything useful.

```
Starting OmniSharp server at 11/11/2020, 19:42:23
    Target: u:\repo\src\MyCourse

OmniSharp server started.
    Path: c:\Users\brigh\.vscode\extensions\ms-dotnettools.csharp-1.23.5\.omnisharp\1.37.3\OmniSharp.exe
    PID: 19888

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.6.30225.117 - "D:\Programmi\VS2019\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\brigh\.vscode\extensions\ms-dotnettools.csharp-1.23.5\.omnisharp\1.37.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.6.30225.117 - "D:\Programmi\VS2019\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'u:\repo\src\MyCourse'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'u:\repo\src\MyCourse'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'u:\repo\src\MyCourse\MyCourse.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'u:\repo\src\MyCourse'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: u:\repo\src\MyCourse\MyCourse.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'u:\repo\src\MyCourse' on host 3416.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'u:\repo\src\MyCourse\MyCourse.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'u:\repo\src\MyCourse\MyCourse.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyCourse
```

**Comment by Aldemaro14** [comment]
I got the same problem with Ubuntu 20.04

`.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
`

And OmniSharp logs
`Starting OmniSharp server at 11/11/2020, 11:23:24 PM
    Target: /home/aldemaro/Desktop/DatingApp/DatingApp.sln

OmniSharp server started with Mono 6.12.0 (always).
    Path: /home/aldemaro/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.4-beta.22/omnisharp/OmniSharp.exe
    PID: 211904

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.6.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/home/aldemaro/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.4-beta.22/omnisharp/.msbuild/Current/Bin"
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Mono installed which contains a MSBuild lower than 16.8.0 which is the minimum supported by the configured .NET Core Sdk.
 Try updating Mono to the latest stable or preview version to enable better .NET Core Sdk support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.6.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/aldemaro/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.4-beta.22/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/aldemaro/Desktop/DatingApp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/aldemaro/Desktop/DatingApp/DatingApp.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/aldemaro/Desktop/DatingApp/API/API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/aldemaro/Desktop/DatingApp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/aldemaro/Desktop/DatingApp/API/API.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/aldemaro/Desktop/DatingApp' on host 211779.
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/aldemaro/Desktop/DatingApp/API/API.csproj'.
/home/aldemaro/Desktop/DatingApp/API/API.csproj
/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/aldemaro/Desktop/DatingApp/API/API.csproj

`

**Comment by JoeRobich** [comment]
> [warn]: OmniSharp.CompositionHostBuilder
>         It looks like you have Mono installed which contains a MSBuild lower than 16.8.0 which is the minimum supported by the configured .NET Core Sdk.
>  Try updating Mono to the latest stable or preview version to enable better .NET Core Sdk support.

@Aldemaro14 Sorry you are running into issues. The problem you are running into seems to be different. See this note about using the .NET 5 SDKs - https://github.com/OmniSharp/omnisharp-vscode/blob/master/README.md#note-about-using-net-5-sdks. You need to set `useGlobalMono` to `never` so that the internal Mono will be used.

**Comment by jesshhu** [comment]
Hi @333fred Already done downgrading and upgrading to the releases of vscode, still experiencing issues, as resolution I install Visual Studio Community Edition, and it seems all working fine for now, though its heavy in my machine but its all good now. Thank you for taking my concerns guys! Really appreciate it!

**Comment by rmclemente** [comment]
Hi, all
I'm running into a similar "reference issue" in a very specific scenario: Creating two classes inside the same file and then moving one of them to a new file.
Steps:

1. Negocio class and NegocioTeste class inside the same file.
2. Negocio class has an attribute of type NegocioTeste.
3. On NegocioTeste class declaration line, click on the lightbulb, then on "Move type to NegocioTeste.cs"
4. Even in the same namespace, there is a reference error pointing to the attribute of type NegocioTeste inside Negocio class.

Here's the output:
```
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using FluentValidation;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: Mover tipo para Negocio2.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: Mover tipo para NegocioTeste.cs
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 1109,
  "Command": "/updatebuffer",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Argumento especificado estava fora do intervalo de valores válidos.\\r\\nNome do parâmetro: index\\r\\n   em Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)\\r\\n   em Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)\\r\\n   em OmniSharp.Roslyn.BufferManager.<UpdateBufferAsync>d__8.MoveNext() na D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\BufferManager.cs:linha 85\\r\\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\\r\\n   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   em OmniSharp.Roslyn.CSharp.Services.Buffer.UpdateBufferService.<Handle>d__2.MoveNext() na D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Buffer\\\\UpdateBufferService.cs:linha 23\\r\\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\\r\\n   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   em OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\\r\\n   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   em OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() na D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:linha 230\\r\\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\\r\\n   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   em OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() na D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:linha 131\\r\\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\\r\\n   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   em OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() na D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:linha 215\"",
  "Body": null,
  "Seq": 11946,
  "Type": "response"
```

**Comment by Luciden** [comment]
Same issue

`Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# standalone...
Starting server at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --telemetryLevel all --extensionLogDirectory c:\Users\robertsdj\AppData\Roaming\Code\logs\20231023T143732\window1\exthost\ms-dotnettools.csharp
waiting for named pipe information from server...
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
[stdout] {"pipeName":"\\\\.\\pipe\\97fdecd8-887b-41c4-a3a2-3425091cc1d3"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 2:41:50 PM] [Program] Language server initialized
[LanguageServerHost] [09:41:50.725][Start]initialize
[LanguageServerHost] [09:41:50.740][Start]Initialize
[LanguageServerHost] [09:41:50.876][End]Initialize
[LanguageServerHost] [09:41:50.979][End]initialize
[LanguageServerHost] [09:41:51.315][Start]initialized
[LanguageServerHost] [09:41:51.871][End]initialized
[LanguageServerHost] [09:41:51.934][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
`

**Comment by Luciden** [comment]
Same issue. 

`Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# standalone...
Starting server at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --telemetryLevel all --extensionLogDirectory c:\Users\robertsdj\AppData\Roaming\Code\logs\20231023T143732\window1\exthost\ms-dotnettools.csharp
waiting for named pipe information from server...
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\robertsdj\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
[stdout] {"pipeName":"\\\\.\\pipe\\97fdecd8-887b-41c4-a3a2-3425091cc1d3"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 2:41:50 PM] [Program] Language server initialized
[LanguageServerHost] [09:41:50.725][Start]initialize
[LanguageServerHost] [09:41:50.740][Start]Initialize
[LanguageServerHost] [09:41:50.876][End]Initialize
[LanguageServerHost] [09:41:50.979][End]initialize
[LanguageServerHost] [09:41:51.315][Start]initialized
[LanguageServerHost] [09:41:51.871][End]initialized
[LanguageServerHost] [09:41:51.934][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
`

**Comment by 333fred** [comment]
@Luciden that looks entirely unrelated. This is an issue about the OmniSharp server, which your logs do not indicate you're using. I would suggest opening a new issue and fully describing the problem you're having there.

**Comment by 333fred** [comment]
I'm going to close this issue out. It's been 3 years since it's been reported, and there are no recent reports on OmniSharp with these symptoms. If anyone is still having issues with the OmniSharp server here, I would ask that you file a new issue. Thanks.
