### ISSUE TITLE
Command `Select Project` fails with extension manifest validation error

### ISSUE THREAD

**Issue by mauve** [dotnet/vscode-csharp#4944]
## Steps to Reproduce ##

- Ctrl-Shift-P: "OmniSharp: Select project"
- Error is shown
![image](https://user-images.githubusercontent.com/795800/145546001-f3973341-2847-4c51-be83-20bed9008c43.png)

## Expected Behavior ##

Opens up the project picker.

## Actual Behavior ##

![image](https://user-images.githubusercontent.com/795800/145546111-204eb8bb-fdca-4bda-999e-bd0c1b394e6c.png)

> Command 'OmniSharp: Select Project' resulted in an error (Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators. Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators. The missing proposal must be added...

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.63.0
**C# Extension**: 1.23.17

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.818 [/usr/share/dotnet/sdk]
  3.1.415 [/usr/share/dotnet/sdk]
  5.0.403 [/usr/share/dotnet/sdk]
  6.0.100-rc.1.21458.32 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.11|
|azure-pipelines|ms-azure-devops|1.195.0|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.9.2|
|cpptools|ms-vscode|1.8.0-insiders2|
|csharp|ms-dotnettools|1.23.17|
|dotnet-test-explorer|formulahendry|0.7.7|
|EditorConfig|EditorConfig|0.16.4|
|jupyter|ms-toolsai|2021.11.1001550889|
|jupyter-renderers|ms-toolsai|1.0.4|
|live-server|ms-vscode|0.2.11|
|LiveServer|ritwickdey|5.6.1|
|prettier-vscode|esbenp|9.0.0|
|python|ms-python|2021.12.1559732655|
|sass-indented|syler|1.8.18|
|test-adapter-converter|ms-vscode|0.1.4|
|vetur|octref|0.35.0|
|vscode-azureappservice|ms-azuretools|0.23.0|
|vscode-azurefunctions|ms-azuretools|1.6.0|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestaticwebapps|ms-azuretools|0.9.0|
|vscode-bicep|ms-azuretools|0.4.1008|
|vscode-docker|ms-azuretools|1.18.0|
|vscode-dotnet-runtime|ms-dotnettools|1.5.0|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.4|
|vscode-pylance|ms-python|2021.12.1|
|vscode-test-explorer|hbenl|2.21.1|
|vscode-yaml|redhat|1.2.2|
|vsliveshare|ms-vsliveshare|1.0.5196|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by TanayParikh** [comment]
Getting the same error:

```
Command 'OmniSharp: Select Project' resulted in an error (Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators.
Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators.
The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp)
```

**Comment by JoeRobich** [comment]
Issue was fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/4914. Until a new release is ready you can install this prerelease that includes the fix https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2

**Comment by jesperkristensen** [comment]
Does anyone know how to install an old working version until a fix is released? My VS Code is basically bricked now. (Installing a prerelease sounds a bit scary)

**Comment by PsychoNineSix** [comment]
> Does anyone know how to install an old working version until a fix is released? My VS Code is basically bricked now. (Installing a prerelease sounds a bit scary)

Old version of omnisharp won't work, I believe it was broken by vscode 1.63, so you either move back to 1.62 or install the pre-release of omnisharp.

**Comment by OdisBy** [comment]
> Does anyone know how to install an old working version until a fix is released? My VS Code is basically bricked now. (Installing a prerelease sounds a bit scary)

Omnisharp can't be downgrade, but downgrading vscode you resolve this problem. [https://code.visualstudio.com/updates/v1_62](url)

**Comment by CEbbinghaus** [comment]
Even after installing the latest prerelease this issue still occurs.

![image](https://user-images.githubusercontent.com/31423391/146320999-af2f4ecf-07ff-4e4b-8d15-8b639feadeeb.png)

Is there prerelease versions which don't include the fix and I need to download exactly 1.23.18?

**Comment by tabish121** [comment]
I found that the solution was to completely uninstall the old version and then choose the extension vsix file for my platform from the beta release page and install that:
https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
