### ISSUE TITLE
Omnisharp Can't Find Mono Installation

### ISSUE THREAD

**Issue by killbox998** [dotnet/vscode-csharp#5518]
## Issue Description ##
Omnisharp can't find the mono installation even though in is installed
## Steps to Reproduce ##
Install mono
uncheck "Use Modern Net"
relaunch vscode

## Expected Behavior ##
Omnisharp Launches

## Actual Behavior ##
Omnisharp asks to install mono

### OmniSharp log ###
OmniSharp failed to start because of missing requirements.

## Environment information ##

<details><summary>Mono Version(From Command Line)</summary>
Mono JIT compiler version 6.12.0.107 (tarball Wed Dec  9 21:44:58 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

TLS:           __thread

SIGSEGV:       altstack

Notifications: epoll

Architecture:  amd64

Disabled:      none

Misc:          softdebug 

Interpreter:   yes

LLVM:          yes(610)

Suspend:       hybrid

GC:            sgen (concurrent by default)
</details>
<details><summary>MsBuild Info(From Command Line)</summary>
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.60701
</details>

**VSCode version**: 1.74.2
**C# Extension**: 1.25.2

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (反映任何 global.json):
 Version:   6.0.112
 Commit:    d311a58ee1

运行时环境:
 OS Name:     fedora
 OS Version:  37
 OS Platform: Linux
 RID:         fedora.37-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.112/

global.json file:
  Not found

Host:
  Version:      6.0.12
  Architecture: x64
  Commit:       02e45a41b7

.NET SDKs installed:
  6.0.112 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.12.27|
|cpptools|ms-vscode|1.13.9|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.2|;

</details>

**Comment by slacktracer** [comment]
Did you have any luck, @killbox998?

I'm in the same boat. For almost two days now.

**Comment by rpmccarter** [comment]
Also running into the same issue, Omnisharp v1.25.2, macOS v12.4, happy to give more info if needed but assuming @killbox998 's report is sufficient

**Comment by esklarski** [comment]
I too had the same problem when upgrading from 1.25.0 this morning. Both 1.25.1 and 1.25.2 fail to find the msbuild install. I've tried specifying a path in settings but I am not sure what file/s the extension is even looking for.

**Comment by Treeway7** [comment]
I'm running Fedora 37 in an FNA project. IntelliSense doesn't work at all, but builds seem to work fine (haven't tested it much, but it seems to build and launch without error). This was on an older project that I used Omnisharp on prior to using 1.25.0, on an older project that was already working. I'm being told to install the complete version of mono, despite having `mono-complete` installed properly on my system from [here](https://www.mono-project.com/download/stable/#download-lin).

After downgrading to 1.23.17 (as per the Stack Overflow link above) everything is working properly again.

**Comment by GlacierFox** [comment]
![Screenshot_2023-01-20_12-15-27](https://user-images.githubusercontent.com/9074086/213692925-30980ce9-5a30-4611-8a7e-f6591b6a5e5d.png)
I'm also getting this problem using Fedora 37  @Treeway7 .

I'm also using Unity. I've downgraded to 1.25.0 and things seem to be working as far as I know. I'm pretty new to C# so I haven't actually built anything substantial to test anything.

**Comment by luisvasq** [comment]
I was having the same issue on Fedora 36, but it's now working for me on `1.25.4`. :tada: Probably resolved after https://github.com/OmniSharp/omnisharp-vscode/pull/5484.

I faced another issue with **"Downloading package 'OmniSharp for Linux (Mono / x64)'"** hanging on startup (same as https://github.com/OmniSharp/omnisharp-vscode/issues/1028). In case it is helpful, I fixed it by going to the extension's `package.json` file (`~/.vscode/extensions/ms-dotnettools.csharp-1.25.4-linux-x64/package.json`), and finding the entry in `runtimeDependencies` that matched my system. Then, pointed the `url` to one of the [official releases in the `omnisharp-roslyn` repo](https://github.com/OmniSharp/omnisharp-roslyn/releases/).

In my case, my system's entry was https://github.com/OmniSharp/omnisharp-vscode/blob/09b09bc069e4eefea65ef6d9bb436a0809e5ded5/package.json#L297-L316 and I changed the `url`'s value to `https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.4/omnisharp-linux-x64.zip`.

**Comment by esklarski** [comment]
Installed 1.25.4 this morning and the problem has disappeared for my system. I guess [#5484](https://github.com/OmniSharp/omnisharp-vscode/pull/5484) was the trouble.

**Comment by slacktracer** [comment]
After I saw updates to this issue I went back to it hopeful but 1.25.4 did not help me. It seems I have everything in place but the issue persists...

```
Last metadata expiration check: 0:00:23 ago on Mon 30 Jan 2023 21:03:58 -03.
Package mono-complete-6.12.0.158-0.xamarin.1.epel8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

Well, at least I did not get my hopes too high. 🤷🏼‍♀️

**Comment by Treeway7** [comment]
Omnisharp is working for me now on `1.25.4`, running Mono and FNA!

**Comment by ffxsam** [comment]
This issue is still not fixed for macOS Silicon?

**Comment by thekoc** [comment]
It'll complain "Mono Installation" for the initial launch but works fine if I restart VSCode. Any ideas?

**Comment by nevyn** [comment]
Same issue on v1.25.8 on Ubuntu 20.04

**Comment by chrisbenincasa** [comment]
Getting this on Fedora 38 w/ version 1.25.9

**Comment by JoeRobich** [comment]
Fedora's mono-complete package does not include msbuild unfortunately. I did find a way to install it on Fedora 36 which may still be an option, see https://github.com/dotnet/vscode-csharp/issues/5232#issuecomment-1145504526.

**Comment by chrisbenincasa** [comment]
Interestingly I got this working by aliasing `dotnet msbuild` to `msbuild`

**Comment by esklarski** [comment]
I've since upgraded through to Fedora 38 and the CentOs mono package keeps working fine.

**Comment by quadristan** [comment]
I did what @chrisbenincasa did, and the extension still cannot find mono installation

```
❯ mono --version
Mono JIT compiler version 6.12.0.182 (tarball Thu Jan 19 23:19:38 UTC 2023)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

❯ msbuild --version
MSBuild version 17.4.4+8e9cb2952 for .NET
17.4.4.31401%    

❯ dnf list installed | grep mono-complete
mono-complete.x86_64  6.12.0-11.fc38                      @fedora 
```

**Comment by davl3232** [comment]
Downgrading to 1.25.0 worked for me on an M1 mac. This video shows  the whole setup that worked for me:
https://www.youtube.com/watch?v=3_OejJf_mN8

**Comment by WDeenik** [comment]
I'm running into this issue as well on an ARM mac. After a full restart (quitting vscode in the dock) everything works like it should, but after normally closing the window and reopening it, I get this error.

**Comment by JoeRobich** [comment]
A lot has changed with O# and mono since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
